model:
  vision_encoder: resnet50
  vision_dim: 2048
  text_encoder: sentence-transformers/all-MiniLM-L6-v2
  text_dim: 384
  num_prompts: 16
  prompt_dim: 512
  num_heads: 8
  num_layers: 2
  temperature: 0.07

training:
  batch_size: 16
  num_epochs: 60
  learning_rate: 0.0001
  weight_decay: 0.0005
  lambda_ce: 1.0
  lambda_align: 0.5
  lambda_reg: 0.1

data:
  num_workers: 0
  pin_memory: false
  train_split: 0.8
  val_split: 0.2

optimizer:
  type: adamw
  betas: [0.9, 0.999]
  eps: 1e-8

scheduler:
  type: cosine
  warmup_epochs: 5
  min_lr: 1e-6
